#+TITLE: emacs config file
This file is a literate configuration file for emacs.

* Tools
** Browse the web
We can use =eww= or =browse-url=.

* Interface elements
Remove the audio bell making annoying noises.
#+begin_src elisp
(setq ring-bell-function 'ignore)
#+end_src

Hide the tool and menu bar.
#+begin_src elisp
(tool-bar-mode -1)
(menu-bar-mode -1)
#+end_src

Hide the buffer scrollbar.
#+begin_src elisp
(if (fboundp 'scroll-bar-mode)
    (scroll-bar-mode -1))
#+end_src

Customize the "fringe" on the side of the window.
#+begin_src elisp
(set-fringe-mode nil)
#+end_src

Alias emacs' UI yes-or-no questions, into y-or-n questions.
#+begin_src emacs-lisp
(defalias 'yes-or-no-p 'y-or-n-p)
#+end_src

* Themes
#+begin_src elisp
(load-theme 'modus-vivendi)
#+end_src

* Custom functions
** yank (paste) forward/backward
It is great to be able to "cycle through the copy/paste ring" (used like undo/redo).
#+begin_src emacs-lisp
(defun yank-pop-forwards (args)
  (interactive "p")
  (yank-pop (- args)))
(global-set-key "\M-Y" 'yank-pop-forwards)
#+end_src

** reload/visit this emacs configuraton
Convenience function to visit and reload our emacs configuration files.
#+begin_src emacs-lisp
(defun config-visit()
  "Visit the emacs config directory, to quickly access and make changes."
  (interactive)
  (find-file "~/.emacs.d/"))
(global-set-key (kbd "C-c e") 'config-visit)

;; a function to reload this file
(defun config-reload()
  "Reload the user config, to get the latest saved changes"
  (interactive)
  (load user-init-file))
(global-set-key (kbd "C-c r") 'config-reload)
#+end_src

** Scratch buffer
Find existing or open a new buffer named =*scratch*=, if we killed the
default one.
#+begin_src emacs-lisp
(defun find-scratch-buffer ()
  "Get or create the *scratch* buffer"
  (interactive)
  (switch-to-buffer (get-buffer-create "*scratch*")))
(global-set-key (kbd "C-c b") 'find-scratch-buffer)
#+end_src

*
* Defaults behaviors
** Backup files
Set emacs backup folder to =~/<emacs-dir>/backups=, but also
deactivate the automatic creation of backup and lock files.
#+begin_src emacs-lisp
(setq backup-directory-alist `(("." . (concat user-emacs-directory "backups"))))

;; do not make bakup files and disable auto-save,
;; because of the file artifacts they create
(setq make-backup-files nil)
(setq auto-save-default nil)

;; do not create/use lockfiles (used to prevent colisions, breaks react)
(setq create-lockfiles nil)
#+end_src

** Isolate autogenerated emacs =init.el= to =custom.el=
Emacs stores some configuration in a file, which by default is the
=./init.el= file. This makes vendoring the init.el in Git tricky, so we
can change it to its own file, and load it (otherwise we would not
load our changes through =M-x= =customize=).
#+begin_src emacs-lisp
(setq custom-file (concat user-emacs-directory "custom.el"))
(when (file-exists-p custom-file)
  (load-file custom-file))
#+end_src
** Automatic update file when changed on disk
If a file has been edited (and saved) by an other software, reload the
file buffer in emacs (so we see the latest version).
#+begin_src emacs-lisp
(global-auto-revert-mode)
#+end_src

** Display all white spaces and tabs
Use whitespace-mode globally to always display whitespaces in buffers
(because we like to catch trailling whitespaces and see
indentation). Also, let's not show whitespace-characters in some modes
where it is too annoying to look at.
#+begin_src emacs-lisp
;; define modes NOT using whitespace-mode
(setq-default whitespace-global-modes
              '(not org-mode
                    magit-mode
                    magit-status-mode
                    dired-mode))
(global-whitespace-mode -1)

;; a little hack, so long lines are not marked as errors by whitespace-mode
(setq-default whitespace-line-column 500)
#+end_src

** identation (not spaces)
This or that, but tries to set all to use tabs for indentation.
#+begin_src emacs-lisp
(setq-default indent-tabs-mode nil)
(setq-default tab-width 2)
;; (defvaralias 'c-basic-offset 'tab-width)
;; (defvaralias 'cperl-indent-level 'tab-width)
#+end_src

* Package manager
To use emacs packages, we first need to require its built-in
packagement magement functionnalities.

We can also define additional package archives, where the remote
packages can be downloaded from.
#+begin_src emacs-lisp
(use-package package
  :init
  (require 'package)
  (setq package-enable-at-startup nil)
  (setq package-archives
	      '(("melpa"        . "https://melpa.org/packages/")
	        ("org"          . "https://orgmode.org/elpa/")
	        ("gnu"          . "https://elpa.gnu.org/packages/"))))
#+end_src

Load Emacs Lisp packages, and activate them.
#+begin_src elisp
;; Load Emacs Lisp packages, and activate them.
(package-initialize)
;; Download descriptions of all configured ELPA packages.
(package-refresh-contents)
;; Treat every package as though it had `:ensure t` to download its files
(setq use-package-always-ensure t)
#+end_src

* Packages
** PGP/GPG

*** Easy PGP
#+begin_src elisp
(use-package epg
  :config
  ;; ensure environmental variables required for GPG are set
  (setenv "GPG_AGENT_INFO" nil)
  (setenv "SSH_AUTH_SOCK"
          (car (process-lines "gpgconf" "--list-dirs" "agent-ssh-socket")))
  ;; should be something like
  ;; =/run/user/1000/gnupg/S.gpg-agent.ssh= when working (arch linux)
  )
#+end_src

*** Pinentry
Some docs on these settings is found on [[https://stackoverflow.com/questions/60812866/emacs-gpg-pinentry-el-for-authentication][Stackoverflow1]] and
[[https://emacs.stackexchange.com/questions/70460/tramp-ssh-connection-inside-eshell-with-gpg-key][Stackoverflow2]].

Pinentry should load after =exwm=, so windows system is loaded before.

#+begin_src elisp
(use-package pinentry
  :ensure t

  :config
  (require 'epa-file)
  (epa-file-enable)
  (setq epg-pinentry-mode 'loopback)
  (pinentry-start)

  ;; Uncertain if there are any side effects.
  ;; somehow fixes .org.gpg files saving, that was hanging
  (fset 'epg-wait-for-status 'ignore)

  (require 'org-crypt)
  (org-crypt-use-before-save-magic)

  ;; Use a default gpg key for encrypting `*.org.gpg` files and `org-encrypt-entry`
  ;; pseudo-concat-anonymity for "no-grep".
  (let ((key (concat
	            "0" "D" "E" "5"
	            "CBA2A8FE5321880ED070D784362D37D"
	            "C" "A" "B" "0" "0")))
    (setq epa-file-encrypt-to key)
    (setq org-crypt-key key)))
#+end_src

Be sure that the =pinentry-*= program are well installed, and that
emacs is "requesting the correct one" (=pinentry-gtk-2= is sometimes
default, and gtk2 might be missing).

In =~/.gnupg/gpg-agent.conf= we can add:
#+begin_quote
enable-ssh-support
allow-emacs-pinentry
allow-loopback-pinentry
pinentry-program /usr/bin/pinentry-emacs
#+end_quote

Don't foget to add the keygrip of the GPG managed SSH (authentication,
=[A]= key) to the file =~/.gnupg/sshcontrol=.

#+begin_src bash
# find the keygrip of secret keys (GPG, SSH managed by gpg)
gpg --list-secret-keys --keyid-format LONG --with-keygrip

# check if the ssh-agent has been feeded the key by gpg-agent
ssh-add -l # this should display our key when it works

# check with github if we can connect with our SSH key
# errors as we can't connect with SSH, but should say key is authorized
ssh -v git@github.com
#+end_src

*** auth-source
#+begin_src elisp
(use-package auth-source
  :config
  (setq auth-source-debug t)
  (setq auth-sources '("~/.authinfo.gpg" "~/.authinfo" "~/.netrc")))
#+end_src

Example auth-source usages.
#+begin_src emacs-lisp
;; (auth-source-search :max 3)
;; (auth-source-search :max 1
;;                    :host system-name
;;                    :require '(:user :secret))
#+end_src

** Git
#+begin_src elisp
(use-package magit)
#+end_src

Highlights git diffs in the margit (fringe) of files, and dired
buffers, when in a git repository.
#+begin_src emacs-lisp
(use-package diff-hl
  :ensure t
  :config
  (global-diff-hl-mode)
  (diff-hl-margin-mode 1)
  (diff-hl-dired-mode 1))
#+end_src

** org-mode
We need to tell org mode to not indent some stuff too much, otherwise
it looks bad on git{hub/lab}, and for *all other people*.

See [[https://emacs.stackexchange.com/questions/16652/change-the-behavior-of-org-mode-auto-expand-relative-path-in-link][this stackoverflow for org-link-file-path-type]]

#+begin_src emacs-lisp
(use-package org
  :config
  ;; hide emphasis markup,italics, bold, code etc.
  (setq org-hide-emphasis-markers t)

  ;; does not indent new lines to match headings indentation
  (setq org-adapt-indentation nil)

  ;; for https://gitlab.com/sctlib/emacs-ssg
  ;; (setq org-link-file-path-type 'relative)

  (setq org-src-preserve-indentation nil)

  ;; do not indent source block root
  (setq org-edit-src-content-indentation 0))
#+end_src

** images
Emacs does not support =webp= image format by default. =imagemagick=
or =ffmpeg= should also be installed on the machine.
#+begin_src emacs-lisp
(use-package image
  :custom
  ;; Enable converting external formats (ie. webp) to internal ones.
  (image-use-external-converter t))
#+end_src

** passwordstore
The standard unix password manager in emacs.

*** pass
#+begin_src emacs-lisp
(use-package pass)
#+end_src

*** password-store
#+begin_src emacs-lisp
(use-package password-store)
#+end_src

*** password-store-otp
One time passwords for 2FA authentication.
#+begin_src emacs-lisp
(use-package password-store-otp)
#+end_src

** ibuffer
Use =ibuffer= instead of =list-buffer=, to switch btw buffers.
#+begin_src elisp
(use-package ibuffer
  :config (global-set-key (kbd "C-x C-b") 'ibuffer))
#+end_src

** editorconfig (to remove in emacs 30, default)
Use editor config files in projects to harmonize tabs/spaces usages
between team members.
#+begin_src emacs-lisp
(use-package editorconfig
  :config
  (editorconfig-mode 1))
#+end_src
** grep
Exclude the following folders from grep search results; for =rgrep=
and =lgrep=.
#+begin_src elisp
(use-package grep
  :config (setq grep-find-ignored-directories '("tmp" "dist" "node_modules")))
#+end_src

** which-key
Display which key shortcut can be used after the already pressed keys;
keychords.
#+begin_src elisp
(use-package which-key
  :config (which-key-mode))
#+end_src

** multiple-cursors
#+begin_src elisp
(use-package multiple-cursors
  :config (setq mc/always-run-for-all t)
  :bind (("C->" . mc/mark-next-like-this)
	       ("C-<" . mc/mark-previous-like-this)
	       ("C-c C->" . mc/mark-all-like-this)
	       ("C-c C-<" . mc/edit-lines)))
#+end_src

** move-text
Move text up and down lines.
#+begin_src elisp
(use-package move-text
  :config (move-text-default-bindings)
  :bind (("M-p" . move-text-up)
	       ("M-n" . move-text-down)))
#+end_src

** ido
#+begin_src emacs-lisp
(use-package ido
  :init
  (ido-mode 1)
  :config
  ;; (ido-everywhere)
  ;; (use-package flx-ido
  ;;   :init (setq ido-enable-flex-matching t)
  ;;   :config (flx-ido-mode 1))
  )
#+end_src
